### PR TITLE
Diversity eligibility requirement

### PR DESCRIPTION
**Pull request by ethanstjohn**
Diversity eligibility requirement. Made eligibility award field optional.

### CODE REVIEW

**Comment by briand44** [comment]
Did you mean to make the background color white or was that left over from previous work?

**Comment by ethanstjohn** [comment]
That was left over from previous work. My fault for including it.

**Comment by briand44** [comment]
It's weird the translate change I see in prod causing the feature to be overridden didn't get included when updating this feature but that's ok.

**Comment by briand44** [comment]
I pushed this change along with the translate change. 4262a6abb72856c5d6c7ffa41889a025febf4bf4

**Pull request closed without merging**
